"""Add autoincrement indices

Revision ID: 7ad1dbec18ae
Revises: ae69526f7543
Create Date: 2023-11-11 10:13:44.160361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad1dbec18ae'
down_revision = 'ae69526f7543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
