"""Refactor tables to conversations

Revision ID: 87a24d9099b9
Revises: 2043967c20b0
Create Date: 2023-11-10 19:36:35.100407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a24d9099b9'
down_revision = '2043967c20b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_id'), 'conversation', ['id'], unique=False)
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participant_conversation_id'), 'participant', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_participant_id'), 'participant', ['id'], unique=False)
    op.create_index(op.f('ix_participant_user_id'), 'participant', ['user_id'], unique=False)
    op.add_column('message', sa.Column('conversation_id', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_message_conversation_id'), 'message', ['conversation_id'], unique=False)
    op.drop_constraint('message_sender_id_fkey', 'message', type_='foreignkey')
    op.drop_constraint('message_receiver_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'conversation', ['conversation_id'], ['id'])
    op.create_foreign_key(None, 'message', 'user', ['user_id'], ['id'])
    op.drop_column('message', 'sender_id')
    op.drop_column('message', 'receiver_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('message', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_receiver_id_fkey', 'message', 'user', ['receiver_id'], ['id'])
    op.create_foreign_key('message_sender_id_fkey', 'message', 'user', ['sender_id'], ['id'])
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message')
    op.drop_column('message', 'user_id')
    op.drop_column('message', 'conversation_id')
    op.drop_index(op.f('ix_participant_user_id'), table_name='participant')
    op.drop_index(op.f('ix_participant_id'), table_name='participant')
    op.drop_index(op.f('ix_participant_conversation_id'), table_name='participant')
    op.drop_table('participant')
    op.drop_index(op.f('ix_conversation_id'), table_name='conversation')
    op.drop_table('conversation')
    # ### end Alembic commands ###
